version: '2.0'
services:
  ews2: 
    image: sparzentny/ews2:latest
    ports:
      - "80:80"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    #volumes:
    # - ./volumes/log/:/root/log/
    # - ./volumes/pids/:/root/tmp/pids/
